### ISSUE TITLE
Load Balancing

### ISSUE THREAD

**Issue by techcto** [codesuki/ecs-gen#2]
Any support for supporting two nodes for a Task in ECS?  It took me a bit to get this working, as it threw an error if there were two nodes with the same Virtual_Host.  First I want to confirm that this does not work yet and is a future task. This was somewhat hard to track down as it caused the container to keep restarting.

Past this, this script works great for one node setups.  Let me know on the load balancing piece, I may have time to look into this later this week. Good job!

**Comment by codesuki** [comment]
Sorry for the late reply! For some reason I was not `watching` this repo. Seems to be the new default now...

@djwinter was so nice to send a pullreq. about exactly this feature I think.
I will merge it today.

After I released, could you confirm if that was your original problem? :)

**Comment by codesuki** [comment]
I released a new version 2 days ago.
