### ISSUE TITLE
Support for multiple exposed ports per task?

### ISSUE THREAD

**Issue by thebadmonkeydev** [codesuki/ecs-gen#24]
My use-case is with a service that exposes an API port and a management web interface on different ports.  Is there any way of supporting multiple exposed ports in a task definition?

**Comment by codesuki** [comment]
You could send a PR to add this (useful) functionality.
Have to make the ports a list somehow here:
https://github.com/codesuki/ecs-gen/blob/master/scanner.go#L120
https://github.com/codesuki/ecs-gen/blob/master/main.go#L22

And then change the nginx template accordingly. The question is how to access the alternative port, maybe add the port number into the hostname like `name-port.domain.com` if there are alternative ports.

**Comment by thebadmonkeydev** [comment]
I'd love to!  Go isn't my first language so I wasn't 100% sure if multiple ports were somehow supported and I couldn't find where.  I'll start working on something.

Honestly, I'm not a huge fan of embedding the port in the hostname, but right this second I'm not sure of a better way.  I'll kick around some ideas and put together a quick PR probably tomorrow.

**Comment by codesuki** [comment]
I didn't like it much either, was just the first thing that came to mind. The host name is the only thing we can influence, I think. So maybe name the ports and add that name to the host name.
Send a PR anytime and I will have a look.
