### ISSUE TITLE
Should find default ECS_REGION

### ISSUE THREAD

**Issue by simplesteph** [codesuki/ecs-gen#8]
I was experiencing the same issue as https://github.com/codesuki/ecs-gen/issues/5

Basically I'm in ap-southeast-2 and my ECS cluster is there. 
Your code finds the cluster because of the log:
```
2017/03/06 03:44:09 found cluster name to be: test-reverse-proxy
```

Your code should also be smart enough to find the region its running in. I don't know Go so can't do a PR, but a way of doing it in bash would be:
```
export AWS_AVAILABILITY_ZONE
AWS_AVAILABILITY_ZONE=$(curl --fail --silent --show-error http://169.254.169.254/latest/meta-data/placement/availability-zone)
export AWS_REGION
AWS_REGION="`echo \"$AWS_AVAILABILITY_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
```

**Comment by codesuki** [comment]
Agree on that. Already on my TODO list 👍

**Comment by Madhu1512** [comment]
submitted PR for this #13

**Comment by codesuki** [comment]
Done.
